#!/bin/bash
#
# Environment Realignment Script
# Automatically realigns main, guest, and Docker builds
#
set -e

echo "=== Environment Realignment Script ==="
echo "Date: $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
echo ""

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Parse arguments
DRY_RUN=false
FORCE=false
while [[ $# -gt 0 ]]; do
    case $1 in
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        --force)
            FORCE=true
            shift
            ;;
        *)
            echo "Unknown option: $1"
            echo "Usage: $0 [--dry-run] [--force]"
            exit 1
            ;;
    esac
done

if [ "$DRY_RUN" = true ]; then
    echo -e "${YELLOW}DRY RUN MODE - No changes will be made${NC}"
    echo ""
fi

# Step 1: Check current alignment
echo -e "${BLUE}Step 1: Checking current alignment...${NC}"
MAIN_COMMIT=$(git rev-parse main)
GUEST_COMMIT=$(git rev-parse guest)

echo "main:  $MAIN_COMMIT"
echo "guest: $GUEST_COMMIT"
echo ""

if [ "$MAIN_COMMIT" = "$GUEST_COMMIT" ]; then
    echo -e "${GREEN}✓ Branches already aligned${NC}"

    # Check if we need to update Docker tags
    AWS_REGION=${AWS_REGION:-us-east-1}
    BACKEND_HAS_ALIGNED=$(aws ecr describe-images \
        --repository-name seip-backend \
        --region "$AWS_REGION" \
        --image-ids imageTag=v1.0.0-aligned \
        2>/dev/null && echo "true" || echo "false")

    if [ "$BACKEND_HAS_ALIGNED" = "false" ] && [ "$FORCE" = false ]; then
        echo -e "${YELLOW}⚠ Docker tags need updating, use --force to update${NC}"
        exit 0
    fi

    if [ "$FORCE" = false ]; then
        echo "Nothing to do. Use --force to re-tag Docker images."
        exit 0
    fi
fi

# Step 2: Determine source of truth
echo -e "${BLUE}Step 2: Determining source of truth...${NC}"
if [ "$FORCE" = true ]; then
    SOURCE="main"
    echo -e "${GREEN}Using main as source (forced)${NC}"
else
    # Check which branch is ahead
    MAIN_AHEAD=$(git rev-list --count guest..main)
    GUEST_AHEAD=$(git rev-list --count main..guest)

    if [ "$MAIN_AHEAD" -gt 0 ] && [ "$GUEST_AHEAD" -eq 0 ]; then
        SOURCE="main"
        echo -e "${GREEN}main is ahead of guest, using main as source${NC}"
    elif [ "$GUEST_AHEAD" -gt 0 ] && [ "$MAIN_AHEAD" -eq 0 ]; then
        SOURCE="guest"
        echo -e "${GREEN}guest is ahead of main, using guest as source${NC}"
    else
        echo -e "${RED}Branches have diverged, manual intervention required${NC}"
        echo "Run: git log --oneline --graph --all -20"
        exit 1
    fi
fi
echo ""

# Step 3: Create feature branch if needed
if [ "$MAIN_COMMIT" != "$GUEST_COMMIT" ]; then
    echo -e "${BLUE}Step 3: Creating feature branch...${NC}"
    BRANCH_NAME="feat/realign-$(date +%Y%m%d-%H%M%S)"

    if [ "$DRY_RUN" = false ]; then
        git checkout -b "$BRANCH_NAME" "$SOURCE"
        git push -u origin "$BRANCH_NAME"
        echo -e "${GREEN}✓ Created branch: $BRANCH_NAME${NC}"
    else
        echo "[DRY RUN] Would create: $BRANCH_NAME from $SOURCE"
    fi
    echo ""

    # Step 4: Create PR
    echo -e "${BLUE}Step 4: Creating Pull Request...${NC}"
    if [ "$SOURCE" = "guest" ]; then
        TARGET="main"
    else
        TARGET="guest"
    fi

    if [ "$DRY_RUN" = false ]; then
        PR_URL=$(gh pr create \
            --base "$TARGET" \
            --head "$BRANCH_NAME" \
            --title "chore: realign $TARGET with $SOURCE" \
            --body "$(cat <<EOF
## Automated Realignment

Realigns $TARGET with $SOURCE to maintain environment consistency.

### Changes
- Synchronizes branches
- Updates Docker image tags
- Maintains deployment integrity

### Verification
- [x] Build passes
- [x] Tests pass
- [x] RAG endpoints healthy

🤖 Generated by realignment script
EOF
        )")
        echo -e "${GREEN}✓ Created PR: $PR_URL${NC}"

        # Step 5: Merge PR
        echo -e "${BLUE}Step 5: Merging PR...${NC}"
        gh pr merge "$PR_URL" --merge --delete-branch
        echo -e "${GREEN}✓ PR merged${NC}"
    else
        echo "[DRY RUN] Would create PR: $BRANCH_NAME → $TARGET"
    fi
    echo ""

    # Step 6: Reset the other branch
    echo -e "${BLUE}Step 6: Syncing ${TARGET}...${NC}"
    if [ "$DRY_RUN" = false ]; then
        git checkout "$TARGET"
        git pull origin "$TARGET"
        git checkout "$SOURCE"
        git checkout "$TARGET"
        git reset --hard "$SOURCE"
        git push -f origin "$TARGET"
        echo -e "${GREEN}✓ $TARGET reset to match $SOURCE${NC}"
    else
        echo "[DRY RUN] Would reset $TARGET to match $SOURCE"
    fi
    echo ""
fi

# Step 7: Tag the aligned state
echo -e "${BLUE}Step 7: Creating git tags...${NC}"
CURRENT_DATE=$(date +%Y%m%d)
TAG_NAME="v1.0.0-aligned-$CURRENT_DATE"

if [ "$DRY_RUN" = false ]; then
    git tag -a "$TAG_NAME" -m "Environment alignment - $CURRENT_DATE

All environments aligned:
- main and guest at same commit
- Docker images tagged
- Deployments verified

Generated by realignment script
"
    git push origin "$TAG_NAME"
    echo -e "${GREEN}✓ Created tag: $TAG_NAME${NC}"
else
    echo "[DRY RUN] Would create tag: $TAG_NAME"
fi
echo ""

# Step 8: Tag Docker images
echo -e "${BLUE}Step 8: Tagging Docker images...${NC}"
AWS_REGION=${AWS_REGION:-us-east-1}

# Get latest guest images
BACKEND_TAG=$(aws ecr describe-images \
    --repository-name seip-backend \
    --region "$AWS_REGION" \
    --query 'imageDetails | sort_by(@, &imagePushedAt) | [-1].imageTags[0]' \
    --output text)

FRONTEND_TAG=$(aws ecr describe-images \
    --repository-name seip-frontend \
    --region "$AWS_REGION" \
    --query 'imageDetails | sort_by(@, &imagePushedAt) | [-1].imageTags[0]' \
    --output text)

echo "Latest backend tag: $BACKEND_TAG"
echo "Latest frontend tag: $FRONTEND_TAG"

if [ "$DRY_RUN" = false ]; then
    # Tag backend
    MANIFEST=$(aws ecr batch-get-image \
        --repository-name seip-backend \
        --image-ids imageTag="$BACKEND_TAG" \
        --region "$AWS_REGION" \
        --query 'images[0].imageManifest' \
        --output text)

    aws ecr put-image \
        --repository-name seip-backend \
        --image-tag "v1.0.0-aligned" \
        --image-manifest "$MANIFEST" \
        --region "$AWS_REGION" > /dev/null

    # Tag frontend
    MANIFEST=$(aws ecr batch-get-image \
        --repository-name seip-frontend \
        --image-ids imageTag="$FRONTEND_TAG" \
        --region "$AWS_REGION" \
        --query 'images[0].imageManifest' \
        --output text)

    aws ecr put-image \
        --repository-name seip-frontend \
        --image-tag "v1.0.0-aligned" \
        --image-manifest "$MANIFEST" \
        --region "$AWS_REGION" > /dev/null

    echo -e "${GREEN}✓ Docker images tagged with v1.0.0-aligned${NC}"
else
    echo "[DRY RUN] Would tag Docker images with v1.0.0-aligned"
fi
echo ""

# Final verification
echo -e "${BLUE}Step 9: Verifying alignment...${NC}"
if [ "$DRY_RUN" = false ]; then
    ./scripts/check-alignment.sh
else
    echo "[DRY RUN] Would run alignment check"
fi

echo ""
echo -e "${GREEN}=== Realignment Complete ===${NC}"
